### ISSUE TITLE
提交订单时的自动滑块总是失败

### ISSUE THREAD

**Issue by Zhouxy5279** [baitianV/autotic#1]
哥们给力，我最近刚好急需，看到好多仓库都多少被针对了一手
有空我也花时间学习改进一下

这个滑块貌似是大麦检测到selenium的手段吧，有时候手动一拖就没问题了，怎么才能在提交这一步越过这个检测呢

**Comment by baitianV** [comment]
我代码已经加了自动解锁的功能了。方法就是用Action模拟手动滑块解锁。

**Comment by Zhouxy5279** [comment]
> 

我的问题是每次尝试拖完进度条都是验证失败，点击窗体重试，是不是需要调什么设置

**Comment by baitianV** [comment]
你用的是我的代码吗？

**Comment by Zhouxy5279** [comment]
那当然是的，就根目录下的Autoticket.py，自动解锁滑轮的这块都是有的

**Comment by Zhouxy5279** [comment]
![image](https://user-images.githubusercontent.com/45713676/186566282-64d2c083-2160-4e44-8280-d155a09f48fe.png)

**Comment by baitianV** [comment]
我再测一下。当时是能通过的。

**Comment by baitianV** [comment]
![image](https://user-images.githubusercontent.com/38852707/186592619-4c509b72-68cf-4d1e-8746-7cb7b54ba9a1.png)
将对应包此处的DEFAULT_MOVE_DURATION参数值改掉。然后更新代码试试。

**Comment by Zhouxy5279** [comment]
我把移动间隔改到了10-30
刚刚也试了不同的移动次数和间隔
我还尝试了第一次不拖到底让它滑回来，然后就有极小概率成功
以上情况大多都会失败，只有极小概率成功，滑块的滑动还有什么讲究吗

**Comment by baitianV** [comment]
我目前的基本可以成功过，不清楚为啥你不行。有更新最新的代码吗？DEFAULT_MOVE_DURATION参数有改掉吗？如果失败次数太多，要关掉浏览器重新尝试的。唯一的讲究就是尽量模仿的像人工滑动吧。

**Comment by Zhouxy5279** [comment]
DEFAULT_MOVE_DURATION就是我说的改成10-30都试过了，而且间隔改短了之后不调整原循环，拖动操作会失效一小部分，代码昨天刚拉的。。
中途也删过cookie，关掉所有网页重试过，我也不清楚为啥老失败，我之后换台电脑再试试吧。其实最后出滑块一瞬间我直接手动操作也是可行的。。。打扰了

**Comment by baitianV** [comment]
我中午刚更新了代码

**Comment by Zhouxy5279** [comment]
。。。。。。那我再更新下

**Comment by Zhouxy5279** [comment]
现在"稳定"了一点，在第三次拖动的时候，一定概率能成功。
有时候第一次就能成功了，感谢老哥

**Comment by baitianV** [comment]
奇怪，我基本都是一次成功，少部分第二次也就成功了。你再琢磨一下滑动频率吧，应该多试试就好了。

**Comment by Zhouxy5279** [comment]
嗯，我也觉得奇怪。可能这个滑块的滑动距离和频率也是有关系。刚刚测试的时候有的场加载后还要点击预填关观演人的确定弹窗，我回去自己琢磨解决一下

**Comment by baitianV** [comment]
后面那个问题我刚更新的代码也解决了
